### ISSUE TITLE
偶发报错panic

### ISSUE THREAD

**Issue by hebo6** [SagerNet/sing#30]
问题描述: 
```
使用clash.meta会偶发的崩溃. 日志定位在sing依赖
```
使用客户端: 
```
clash.mate
```
日志: 
```
panic: close of nil channel
goroutine 8006 [running]:
github.com/sagernet/sing/common/bufio/deadline.(*pipeDeadline).set.func1()
	github.com/sagernet/sing@v0.2.2/common/bufio/deadline/pipe.go:53 +0x24
created by time.goFunc
	time/sleep.go:176 +0x38
```

**Comment by wwqgtxx** [comment]
测试问题请使用最新的alpha版本，你这sing依赖明显就是旧的

**Comment by wxyzh** [comment]
https://github.com/MetaCubeX/Clash.Meta/issues/386
