### ISSUE TITLE
sing-box 出现 Panic

### ISSUE THREAD

**Issue by yaotthaha** [SagerNet/sing#41]
```
goroutine 351 [select, 2 minutes]:
runtime.gopark(0x400059e880?, 0x2?, 0x88?, 0x83?, 0x400099e914?)
	runtime/proc.go:381 +0xe0 fp=0x4000818320 sp=0x4000818300 pc=0x4e9c50
runtime.selectgo(0x400059e880, 0x400099e910, 0x4000818478?, 0x0, 0x4000818478?, 0x1)
	runtime/select.go:327 +0x68c fp=0x4000818430 sp=0x4000818320 pc=0x4fa2ec
reflect.rselect({0x40008185a8, 0x2, 0x400027a6c0?})
	runtime/select.go:589 +0x288 fp=0x40008184c0 sp=0x4000818430 pc=0x517918
reflect.Select({0x40000f83f0?, 0x2, 0x2?})
	reflect/value.go:3052 +0x45c fp=0x4000818630 sp=0x40008184c0 pc=0x5789dc
github.com/sagernet/sing/common.SelectContext({0x400059e760, 0x2, 0x40002321e8?})
	github.com/sagernet/sing@v0.2.5-0.20230517124404-be6013893626/common/context.go:13 +0x19c fp=0x40008186d0 sp=0x4000818630 pc=0x78300c
github.com/sagernet/sing/common/task.(*Group).RunContextList(0x400064d680, {0x40008208f8?, 0x400059e640?, 0xf0c6f8?})
	github.com/sagernet/sing@v0.2.5-0.20230517124404-be6013893626/common/task/task.go:89 +0x340 fp=0x40008187d0 sp=0x40008186d0 pc=0x7a46d0
github.com/sagernet/sing/common/bufio.CopyConnContextList({0x40008208f8, 0x1, 0x1}, {0x1cb1240?, 0x400059e640}, {0x1cb3028?, 0x4000218208})
	github.com/sagernet/sing@v0.2.5-0.20230517124404-be6013893626/common/bufio/copy.go:246 +0x6a4 fp=0x4000818860 sp=0x40008187d0 pc=0x850734
github.com/sagernet/sing/common/bufio.CopyConn(...)
	github.com/sagernet/sing@v0.2.5-0.20230517124404-be6013893626/common/bufio/copy.go:206
github.com/sagernet/sing-box/outbound.CopyEarlyConn({0x1ca6ae0, 0x400064d530}, {0x1cb1240?, 0x400059e640}, {0x1cb3028, 0x4000218208})
	github.com/sagernet/sing-box/outbound/default.go:128 +0x554 fp=0x4000820940 sp=0x4000818860 pc=0xf97fb4
github.com/sagernet/sing-box/outbound.NewConnection({_, _}, {_, _}, {_, _}, {{0x4000329cb0, 0x9}, {0x17a3161, 0x6}, ...})
	github.com/sagernet/sing-box/outbound/default.go:58 +0x19c fp=0x40008209f0 sp=0x4000820940 pc=0xf9746c
github.com/sagernet/sing-box/outbound.(*Direct).NewConnection(_, {_, _}, {_, _}, {{0x4000329cb0, 0x9}, {0x17a3161, 0x6}, 0x0, ...})
	github.com/sagernet/sing-box/outbound/direct.go:192 +0x74 fp=0x4000820bc0 sp=0x40008209f0 pc=0xf99cb4
github.com/sagernet/sing-box/route.(*Router).RouteConnection(_, {_, _}, {_, _}, {{0x4000329cb0, 0x9}, {0x17a3161, 0x6}, 0x0, ...})
	github.com/sagernet/sing-box/route/router.go:720 +0x1a9c fp=0x4000821650 sp=0x4000820bc0 pc=0x10cc2ac
github.com/sagernet/sing-box/inbound.(*myInboundAdapter).newConnection(_, {_, _}, {_, _}, {{0x4000329cb0, 0x9}, {0x17a3161, 0x6}, 0x0, ...})
	github.com/sagernet/sing-box/inbound/default.go:124 +0x110 fp=0x4000821820 sp=0x4000821650 pc=0x1032be0
github.com/sagernet/sing-box/inbound.(*TProxy).NewConnection(_, {_, _}, {_, _}, {{0x4000329cb0, 0x9}, {0x17a3161, 0x6}, 0x0, ...})
	github.com/sagernet/sing-box/inbound/tproxy.go:79 +0x128 fp=0x4000821a80 sp=0x4000821820 pc=0x1044b18
github.com/sagernet/sing-box/inbound.(*myInboundAdapter).injectTCP(_, {_, _}, {{0x4000329cb0, 0x9}, {0x17a3161, 0x6}, 0x0, {0x0, 0x0}, ...})
	github.com/sagernet/sing-box/inbound/default_tcp.go:62 +0x180 fp=0x4000821e10 sp=0x4000821a80 pc=0x1033f30
github.com/sagernet/sing-box/inbound.(*myInboundAdapter).loopTCPIn.func1()
	github.com/sagernet/sing-box/inbound/default_tcp.go:54 +0x64 fp=0x4000821fd0 sp=0x4000821e10 pc=0x1033d74
runtime.goexit()
	runtime/asm_arm64.s:1172 +0x4 fp=0x4000821fd0 sp=0x4000821fd0 pc=0x51c064
created by github.com/sagernet/sing-box/inbound.(*myInboundAdapter).loopTCPIn
	github.com/sagernet/sing-box/inbound/default_tcp.go:54 +0x2fc
```

日志信息无法保存

**Comment by nekohasekai** [comment]
这不是 panic 信息，只是当前上下文的一部分，没有信息。
