### ISSUE TITLE
panic: sync/atomic: store of inconsistently typed value into Value

### ISSUE THREAD

**Issue by Billyzou0741326** [SagerNet/sing#58]
In the past few days I've been running into this error:

```
panic: sync/atomic: store of inconsistently typed value into Value
goroutine 597 [running]:
sync/atomic.(*Value).Store(0xc000312030, {0x1619680, 0xc0002f3a40})
	sync/atomic/value.go:78 +0xd5
github.com/sagernet/sing/common/atomic.(*TypedValue[...]).Store(...)
	github.com/sagernet/sing@v0.3.5/common/atomic/typed.go:22
github.com/sagernet/sing/protocol/http.HandleConnection.func1.1()
	github.com/sagernet/sing@v0.3.5/protocol/http/handshake.go:130 +0xc8
created by github.com/sagernet/sing/protocol/http.HandleConnection.func1 in goroutine 596
	github.com/sagernet/sing@v0.3.5/protocol/http/handshake.go:127 +0x20a
```

My setup uses [v2rayN@6.38](https://github.com/2dust/v2rayN/releases/tag/6.38) and [sing-box-1.8.8-windows-amd64](https://github.com/SagerNet/sing-box/releases/tag/v1.8.8), which I assume is using [sing@v0.3.5](https://github.com/SagerNet/sing/releases/tag/v0.3.5).

My first guess is that `hErr`'s type is incorrect:

https://github.com/SagerNet/sing/blob/ec2595f010e2edb4790ba2c2447a8543182e3012/protocol/http/handshake.go#L128-L130

But I'm not super familiar with the codebase yet. I will try to debug further when I have time.

Meanwhile, just wanted to report it here and see if anyone else knows what might be going wrong here.

**Update 1**: Looking through the commit history brought my attention to this commit https://github.com/SagerNet/sing/commit/a4a9ec42c6285a6a2463cc39ad42884ecd94f5fa so it got introduced in `v0.3.4`. As a first attempt I'm going to revert back to `v0.3.3` or earlier and see what happens

**Final update**: Versions **v0.3.3** (or lower) and **v0.3.6** (or above) works.

**Comment by Billyzou0741326** [comment]
Sure, I'll point my build to use `sing@v0.3.6` and see how that goes. Will report back in a few hours (sometimes the error take some time to come up).

**Comment by Billyzou0741326** [comment]
Ok, I've been running `v0.3.6` for a while now, and there were no signs of the panic. Apparently `v0.3.6` already got rid of the issue.

For anyone else running into this problem, use versions **`v0.3.3`** (or lower) or **`v0.3.6`** (or above).

Thanks a lot @nekohasekai and @wwqgtxx for looking into this. Closing this issue.
